# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa658112553d367bde364415f5de385d261d7d746934f6ade9de6527544583e303729c8c3a29778399588b1e2d68604ed28e3255dd04ab8d63a7e1fcc7fcb6da

test:
  secret_key_base: 4946578ec1e2da0060b9bf1ea6b2d03e3701107416a5a7b843f0c0ef984f5bde101c9cbdff14dd92173e6b5f9df8fe9969a6806e397c0baafdda43a11b9c739d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
